#!/usr/bin/env bash
set -eu

# assumes:
# groupadd library
# groupadd morrigan

function yes_or_no {
  while true; do
    read -p "$* [y/n]: " yn
    case $yn in
      [Yy]*) return 0  ;;
      [Nn]*) echo "Aborted" ; return  1 ;;
    esac
  done
}

r="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
jar="$r/target/morrigan-1-SNAPSHOT-jar-with-dependencies.jar"
if ! [ -e "$jar" ] ; then
  echo "Not found: $jar"
  echo 'Maybe try building with: mvn clean package'
  exit 1
fi
echo "Using jar: $jar"

insdir="/opt/morrigan"
echo "Install dir: $insdir"

mkdir -vp "$insdir"
cp -v "$jar" "$insdir/morrigan.jar"

homedir="$insdir/home"
mkdir -vp "$homedir"
chgrp -v 'morrigan' "$homedir"
chmod -v 770 "$homedir"
chmod g+s "$homedir"

unit_src="$r/systemd/morrigan.service"
unit_etc='/etc/systemd/system/morrigan.service'
if [ -e "$unit_etc" ] ; then
  if ! diff "$unit_src" "$unit_etc" ; then
    yes_or_no "Installed unit file differs, continue?" || exit 1
  fi
else
  cp -v "$unit_src" "$unit_etc"
fi

systemctl daemon-reload
systemctl enable  morrigan
systemctl restart morrigan
systemctl status  morrigan
