#!/bin/bash
set -eu

print_help() {
  echo "Usage: $0 <plugin> [jar_path]"
  echo "Available plugins:"
  echo "  sshui"
  echo "  dlna"
  exit 0
}

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ] ; then print_help ; fi

arg_name="$1"
if [ "$arg_name" == "sshui" ] ; then
  bname="com.vaguehope.morrigan.sshui"
elif [ "$arg_name" == "dlna" ] ; then
  bname="com.vaguehope.morrigan.dlna"
else
  echo "Unknown plugin: $arg_name"
  print_help
fi

mndir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Morrigan: $mndir"
echo "Bundle: $bname"

ljarname="$bname.jar"
jarlocal="$mndir/plugins/$ljarname"

arg_jar="${2:-}"
if [ -n "$arg_jar" ] ; then
  if [ -e "$arg_jar" ] ; then
    echo -e "Copying:\n  $arg_jar\n  --> $jarlocal"
    cp "$arg_jar" "$jarlocal"
  else
    echo "Not found: $arg_jar"
    exit 1
  fi
else
  extrajar="extras/$bname-*.jar"
  if [ -e "$extrajar" ] ; then
    echo "Jar: $extrajar"
    cp "$extrajar" "$jarlocal"
  else
    echo "Not found: $extrajar"
    exit 1
  fi
fi

conf="$mndir/configuration/config.ini"
echo "Config: $conf"

if ! [ -e "$conf" ] ; then
  echo "File not found: $conf"
  exit 1
fi

if ! grep -q "$ljarname" "$conf" ; then
  sed "-i.$(date +'%Y%m%d-%H%M%S').bak" "/^osgi.bundles=/s/$/,reference\\\\:file\\\\:$ljarname@4\\\\:start/" "$conf"
else
  echo "$conf already contains $ljarname."
fi

echo "done."
