#!/bin/bash
set -eu

print_help() {
  echo "Usage: $0 <plugin>"
  echo "Available plugins:"
  echo "  sshui"
  exit 0
}

if [ "$#" -lt 1 ] || [ "$#" -gt 1 ] ; then print_help ; fi

arg_name="$1"
if [ "$arg_name" == "sshui" ] ; then
  bname="com.vaguehope.morrigan.sshui"
else
  echo "Unknown plugin: $arg_name"
  print_help
fi

mndir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Morrigan directory: $mndir"

jarname="$(curl --silent "http://karasu.vaguehope.com/plugins.rhtml" | grep "$bname" | head -n 1)"
if [ -z "$jarname" ] ; then
  echo "Not found in plugin list: $bname"
  exit 1
fi

jarurl="http://karasu.vaguehope.com/$jarname"
jarlocal="$mndir/plugins/$jarname"
echo "Downloading $jarurl --> $jarlocal"
curl "$jarurl" -o "$jarlocal"

conf="$mndir/configuration/config.ini"
echo "config: $conf"

if ! [ -e "$conf" ] ; then
  echo "File not found: $conf"
  exit 1
fi

if ! grep -q "$jarname" "$conf" ; then
  sed "-i.$(date +'%Y%m%d-%H%M%S').bak" "/^osgi.bundles=/s/$/,reference\\\\:file\\\\:$jarname@4\\\\:start/" "$conf"
else
  echo "$conf already contains $jarname."
fi

echo "done."
