#!/bin/bash
set -eu -o pipefail
shopt -s failglob

# Generate keys:
# cd ~/.morrigan/keys
# openssl genpkey -out "${HOST}-private.pem" -outform PEM -algorithm RSA -pkeyopt rsa_keygen_bits:4096
# openssl req -x509 -days 365 -new -subj "/C=XX/ST=X/L=X/O=X/OU=X/CN=${HOST}" -key "${HOST}-private.pem" -out "${HOST}-public.pem"
# cp "${HOST}-public.pem" ~/Dropbox/Apps/morrigan/

HOST="$(hostname)"

mndbs=( "$HOME"/opt/morrigan*/mndb )
mndb="${mndbs[0]}"
if ! [ -e "$mndb" ] ; then
  echo "Not found: $mndb"
  exit 1
fi

db_files=( "$HOME/.morrigan/mmdb/"*.local.db3 )
keys=( "$HOME/Dropbox/Apps/morrigan/"*-public.pem )

for db_file in "${db_files[@]}" ; do
  db_basename="$(basename "$db_file")"
  db_name="${db_basename%.local.db3}"
  out="$HOME/Dropbox/Apps/morrigan/${HOST}-${db_name}.xml.cms"
  echo "$db_name > $out ..."
  $mndb dump "$db_name" \
    | gzip \
    | openssl cms -encrypt -binary -aes256 -outform der -out "$out" "${keys[@]}"
done

echo "done."
