#!/bin/bash
set -eu -o pipefail
shopt -s failglob

print_help() {
  echo "Usage:"
  echo "  $0 dump <db-name> > file.xml"
  echo "  $0 remotes <db-name>"
  echo "  $0 pull <db-name> <remote-name>"
  exit 1
}

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ] ; then print_help ; fi

cmd="$1"
db_name="$2"
remote_name="${3:-}"

props=$(< "$HOME/.morrigan/server.properties")
user="u"
host="localhost"
passwd="$(echo "$props" | awk -F= '/^pass=/ {print $2}')"
port="$(echo "$props" | awk -F= '/^port=/ {print $2}')"
mn_uri="http://${user}:${passwd}@${host}:${port}" # TODO don't leak passwd via process args.
db_uri="$mn_uri/mlists/LOCALMMDB/${db_name}.local.db3"

do_dump() {
  items_uri="${db_uri}/items?includeddeletedtags=true"
  curl --silent "$items_uri"
}

do_remotes() {
  res="$(curl --silent "$db_uri")"
  echo "$res" | awk 'match($0, /<remote>([^<]+)<\/remote>/, a) {print a[1]}'
}

do_pull() {
  if [ -z "$remote_name" ] ; then print_help ; fi
  res="$(curl --silent -d "action=pull&remote=${remote_name}" "$db_uri")"
  task_id="$(echo "$res" | awk -F= '/^id=/ {print $2}')"
  echo "Waiting for task ${task_id} ..."
  task_uri="$mn_uri/status/$task_id"
  res=""
  while true ; do
    res="$(curl --silent "$task_uri")"
    state="$(echo "$res" | awk 'match($0, /<state>([^<]+)<\/state>/, a) {print a[1]}')"
    if [ "$state" = "COMPLETE" ] ; then break ; fi
    echo -n '.'
    sleep 5
  done
  successful="$(echo "$res" | awk 'match($0, /<successful>([^<]+)<\/successful>/, a) {print a[1]}')"
  if [ "$successful" = "true" ] ; then
    echo "Success."
  else
    err="$(echo "$res" | awk 'match($0, /<lastErr>([^<]+)<\/lastErr>/, a) {print a[1]}')"
    echo "Failed: $err"
    exit 1
  fi
}

case "$cmd" in
  dump)
    do_dump
    ;;
  remotes)
    do_remotes
    ;;
  pull)
    do_pull
    ;;
  *)
    echo "Unknown cmd: $cmd" >&2
    exit 1
    ;;
esac
