#!/bin/bash
set -eu -o pipefail
shopt -s failglob

print_help() {
  echo "Usage:"
  echo "  $0 dump <db-name> > file.xml"
  echo "  $0 remotes <db-name>"
  echo "  $0 pull <db-name> <remote-name>"
  echo "  $0 playpause"
  echo "  $0 next"
  exit 1
}

if [ "$#" -lt 1 ] || [ "$#" -gt 3 ] ; then print_help ; fi

cmd="$1"
db_name="${2:-}"
remote_name="${3:-}"

props=$(< "$HOME/.morrigan/server.properties")
user="u"
host="localhost"
passwd="$(echo "$props" | awk -F= '/^pass=/ {print $2}')"
port="$(echo "$props" | awk -F= '/^port=/ {print $2}')"
mn_uri="http://${user}:${passwd}@${host}:${port}" # TODO don't leak passwd via process args.
db_uri="$mn_uri/mlists/LOCALMMDB/${db_name}.local.db3"
auto_uri="$mn_uri/players/auto"

do_dump() {
  if [ -z "$db_name" ] ; then print_help ; fi

  items_uri="${db_uri}/items?includeddeletedtags=true"
  if ! curl --fail --silent "$items_uri" ; then
    echo "Morrigan API request failed." >&2
    exit 1
  fi
}

do_remotes() {
  if [ -z "$db_name" ] ; then print_help ; fi

  if ! res="$(curl --fail --silent "$db_uri")" ; then
    echo "Morrigan API request failed." >&2
    exit 1
  fi
  echo "$res" | awk 'match($0, /<remote>([^<]+)<\/remote>/, a) {print a[1]}'
}

do_pull() {
  if [ -z "$db_name" ] ; then print_help ; fi
  if [ -z "$remote_name" ] ; then print_help ; fi

  if ! res="$(curl --fail --silent -d "action=pull&remote=${remote_name}" "$db_uri")" ; then
    echo "Morrigan API request failed." >&2
    exit 1
  fi
  task_id="$(echo "$res" | awk -F= '/^id=/ {print $2}')"
  echo "Waiting for task ${task_id} ..."
  task_uri="$mn_uri/status/$task_id"
  res=""
  while true ; do
    if ! res="$(curl --fail --silent "$task_uri")" ; then
      echo "Morrigan API request failed." >&2
      exit 1
    fi
    state="$(echo "$res" | awk 'match($0, /<state>([^<]+)<\/state>/, a) {print a[1]}')"
    if [ "$state" = "COMPLETE" ] ; then break ; fi
    echo -n '.'
    sleep 5
  done
  successful="$(echo "$res" | awk 'match($0, /<successful>([^<]+)<\/successful>/, a) {print a[1]}')"
  if [ "$successful" = "true" ] ; then
    echo "Success."
  else
    err="$(echo "$res" | awk 'match($0, /<lastErr>([^<]+)<\/lastErr>/, a) {print a[1]}')"
    echo "Failed: $err"
    exit 1
  fi
}

do_playpause() {
  if ! res="$(curl --fail --silent "$auto_uri" -d 'action=playpause')" ; then
    echo "Morrigan API request failed." >&2
    exit 1
  fi
}

do_next() {
  if ! res="$(curl --fail --silent "$auto_uri" -d 'action=next')" ; then
    echo "Morrigan API request failed." >&2
    exit 1
  fi
}

case "$cmd" in
  dump)
    do_dump
    ;;
  remotes)
    do_remotes
    ;;
  pull)
    do_pull
    ;;
  playpause)
    do_playpause
    ;;
  next)
    do_next
    ;;
  *)
    echo "Unknown cmd: $cmd" >&2
    exit 1
    ;;
esac
