"C:\Program Files\Java\jdk1.6.0_17\bin\javaw.exe" ^
-Dosgi.requiredJavaVersion=1.5 -Xms40m -Xmx256m ^
-Djava.util.logging.config.file=logging.properties ^
-Dfile.encoding=UTF-8 ^
-classpath C:\Software\eclipsercpgalileo\plugins\org.eclipse.equinox.launcher_1.0.201.R35x_v20090715.jar org.eclipse.equinox.launcher.Main ^
-launcher C:\Software\eclipsercpgalileo\eclipse.exe ^
-name Eclipse ^
-showsplash 600 ^
-product net.sparktank.morrigan.product ^
-configuration file:D:/haku/development/eclipseWorkspace-java/.metadata/.plugins/org.eclipse.pde.core/net.sparktank.morrigan.application/ ^
-dev file:D:/haku/development/eclipseWorkspace-java/.metadata/.plugins/org.eclipse.pde.core/net.sparktank.morrigan.application/dev.properties ^
-os win32 -ws win32 -arch x86 -nl en_GB -consoleLog -console
